name: bilibili-live-check-in
on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 16 * * *
env:
  TZ: Asia/Shanghai
jobs:
  check-in-job:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v2
      - name: set up
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: check in
        run: go run main.go
        env:
          COOKIE: ${{secrets.COOKIE}}
          CSRF: ${{secrets.CSRF}}
          ROOM_ID: ${{secrets.ROOM_ID}}